---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istiod
    targetRevision: 1.22.0
    helm:
      valuesObject:
        # Istiod control plane configuration
        global:
          istioNamespace: istio-system
          
        # Pilot (istiod) configuration
        pilot:
          # Production-ready resource requests and limits
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 1000m
              memory: 4Gi
          
          # Enable auto-scaling for production
          autoscaleEnabled: true
          autoscaleMin: 2
          autoscaleMax: 5
          
          # High availability settings
          replicaCount: 2
          
          # Enable pod disruption budget for stability
          podDisruptionBudget:
            minAvailable: 1
          
          # Enable configuration validation
          configValidation: true
          
          # CPU target for autoscaling
          cpu:
            targetAverageUtilization: 80
          
          # Enable tracing for observability (adjust based on your backend)
          traceSampling: 1.0
          
        # Security and mTLS settings
        meshConfig:
          # Enable automatic mTLS
          enableAutoMtls: true
          
          # Default config for proxies
          defaultConfig:
            # Holdoff before proxy starts accepting traffic
            holdApplicationUntilProxyStarts: true
            
            # Proxy resource configuration
            proxyMetadata: {}
            
        # Telemetry configuration
        telemetry:
          enabled: true
          v2:
            enabled: true
            prometheus:
              enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
